export const ADD_SOURCE_REQUEST = 'ADD_SOURCE_REQUEST';
export const ADD_SOURCE_SUCCESS = 'ADD_SOURCE_SUCCESS';
export const ADD_SOURCE_FAILURE = 'ADD_SOURCE_FAILURE';

export const UPDATE_SOURCE_REQUEST = 'UPDATE_SOURCE_REQUEST';
export const UPDATE_SOURCE_SUCCESS = 'UPDATE_SOURCE_SUCCESS';
export const UPDATE_SOURCE_FAILURE = 'UPDATE_SOURCE_FAILURE';

export const DELETE_SOURCES_REQUEST = 'DELETE_SOURCES_REQUEST';
export const DELETE_SOURCES_SUCCESS = 'DELETE_SOURCES_SUCCESS';
export const DELETE_SOURCES_FAILURE = 'DELETE_SOURCES_FAILURE';

export const GET_SOURCE_REQUEST = 'GET_SOURCE_REQUEST';
export const GET_SOURCE_SUCCESS = 'GET_SOURCE_SUCCESS';
export const GET_SOURCE_FAILURE = 'GET_SOURCE_FAILURE';