export const GET_RESOURCES_REQUEST = 'GET_RESOURCES_REQUEST';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAILURE = 'GET_RESOURCES_FAILURE';

export const GET_PLUGINS_REQUEST = 'GET_PLUGINS_REQUEST';
export const GET_PLUGINS_SUCCESS = 'GET_PLUGINS_SUCCESS';
export const GET_PLUGINS_FAILURE = 'GET_PLUGINS_FAILURE';

export const UPDATE_PLUGINS_SUCCESS = 'UPDATE_PLUGINS_SUCCESS';
export const UPDATE_PLUGINS_FAILURE = 'UPDATE_PLUGINS_FAILURE';
export const UPDATE_PLUGINS_REQUEST = 'UPDATE_PLUGINS_REQUEST';