export const ADD_WORKSPACE_REQUEST = 'ADD_WORKSPACE_REQUEST';
export const ADD_WORKSPACE_SUCCESS = 'ADD_WORKSPACE_SUCCESS';
export const ADD_WORKSPACE_FAILURE = 'ADD_WORKSPACE_FAILURE';

export const UPDATE_WORKSPACE_REQUEST = 'UPDATE_WORKSPACE_REQUEST';
export const UPDATE_WORKSPACE_SUCCESS = 'UPDATE_WORKSPACE_SUCCESS';
export const UPDATE_WORKSPACE_FAILURE = 'UPDATE_WORKSPACE_FAILURE';

export const DELETE_WORKSPACES_REQUEST = 'DELETE_WORKSPACES_REQUEST';
export const DELETE_WORKSPACES_SUCCESS = 'DELETE_WORKSPACES_SUCCESS';
export const DELETE_WORKSPACES_FAILURE = 'DELETE_WORKSPACES_FAILURE';

export const GET_WORKSPACE_REQUEST = 'GET_WORKSPACE_REQUEST';
export const GET_WORKSPACE_SUCCESS = 'GET_WORKSPACE_SUCCESS';
export const GET_WORKSPACE_FAILURE = 'GET_WORKSPACE_FAILURE';

export const GET_LIST_WORKSPACES_REQUEST = 'GET_LIST_WORKSPACES_REQUEST';
export const GET_LIST_WORKSPACES_SUCCESS = 'GET_LIST_WORKSPACES_SUCCESS';
export const GET_LIST_WORKSPACES_FAILURE = 'GET_LIST_WORKSPACES_FAILURE';